# Generated by Django 4.0.3 on 2022-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
