# Generated by Django 3.2.8 on 2022-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='father_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
