# Generated by Django 3.2.8 on 2022-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.TextField(default='', null=True),
        ),
    ]
