# Generated by Django 3.2.8 on 2022-04-10 22:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('father_name', models.CharField(default=None, max_length=300)),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('profile_picture', models.URLField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=300)),
                ('short_description', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('students', models.ManyToManyField(to='attendance.Student')),
            ],
        ),
    ]
