# Generated by Django 3.2.8 on 2022-04-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_classroom_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
