# Generated by Django 4.0.3 on 2022-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
