# Generated by Django 4.0.3 on 2022-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_classroom_instructor_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='excel_sheet_path',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='dsd', max_length=300),
            preserve_default=False,
        ),
    ]
